accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'login/$',
    auth_views.LoginView.as_view(template_name='accounts/login.html'),
    name='login'),
    url(r'logout/$',auth_views.LogoutView.as_view(),name='logout'),
    url(r'signup/$',views.SignUp.as_view(),name='signup'),
]

attendance/urls.py
from django.conf.urls import url, include
from attendance import views
from datetime import datetime

app_name = 'attendance'

urlpatterns = [
    url(r'^mark/$',views.CreateSessionView.as_view(),name='create'),
    url(r'^list/$',views.DetailSessionView.as_view(),name='list'),
]


# S = str(datetime.now().time()).strip(':')
# A = [int(i) for i in S.replace('.', ':').split(':')]
# if (A[0] == 9 and A[1] in range(0,31)) | (A[0] in range(18,22) and A[1] in range(0,61)):
#     urlpatterns = [
#         url(r'^mark/$',views.CreateSessionView.as_view(),name='create'),
#     ] + urlpatterns
# else:
#     urlpatterns = [
#         url(r'^index/$',views.IndexPageView.as_view(),name='indexpage'),
#     ] + urlpa

simplesocial/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.HomePage.as_view(),name='home'),
    url(r'^test/$', views.TestPage.as_view(),name='test'),
    url(r'^thanks/$', views.ThanksPage.as_view(),name='thanks'),
    url(r'^accounts/',include('accounts.urls',namespace='accounts')),
    url(r'^accounts/',include('django.contrib.auth.urls')),
    url(r'^attendance/',include('attendance.urls', namespace='attendance')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

accounts/models.py
from django.db import models
from django.contrib import auth
# Create your models here.

class User(auth.models.User,auth.models.PermissionsMixin):

    def __str__(self):
        return "@{}".format(self.username)

attendance/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth import get_user_model
User = get_user_model()
from django.contrib.auth.models import User
from django.utils import timezone
from datetime import datetime
from django.http import HttpResponse
from django.utils.timezone import localtime, now

# from django.conf import settings
# User = settings.AUTH_USER_MODEL

D = datetime.now()

# Day
F = D.strftime("%A")

# Time
G = D.strftime("%I:%M:%S%p")

# Session
S = str(datetime.now().time()).strip(':')
A = [int(i) for i in S.replace('.', ':').split(':')]
if A[0] == 9 and A[1] in range(0,61):
    # CHOICES=[('Morning','Morning')]
    CHOICE=[
        ("Morning","Morning")
            ]
elif A[0] in range(14,16) and A[1] in range(0,61):
    CHOICE=[
        ("Evening","Evening")
            ]
else:
    CHOICE= [
        ("","Please Come Back at the Specified Time. For more details, visit Home Page")
            ]

# CHOICES=[('Morning','Morning'),('Evening','Evening')]
class Session(models.Model):
    user = models.ForeignKey(User)
    session = models.CharField(max_length=50,choices=CHOICE,default="NoAttendance")

    t_date = models.DateTimeField(default=timezone.now,blank=True)
    only_date = models.DateField(default=timezone.now().today,blank=True)




    def __str__(self):
        return "{} {} {}".format(self.user_id,self.session,str(self.t_date))

    def get_absolute_url(self):
        return reverse("attendance:create")

    def save(self, *args, **kwargs):

        # if self.session!= 'Morning' and self.session != 'Evening':
        #     return reverse("attendance:create")

        if self.session != '':
            conflicting_instance = Session.objects.filter(session=self.session, only_date=self.only_date, user=self.user_id)
            if self.id:
                # This instance has already been saved. So we need to filter out
                # this instance from our results.
                conflicting_instance = conflicting_instance.exclude(pk=self.id)

            if conflicting_instance.exists():
                return HttpResponse('Attendance already Marked!!!.')

        super(Session, self).save(*args, **kwargs)

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

class UserCreateForm(UserCreationForm):

    class Meta:
        fields = ('username','email','password1','password2')
        model = get_user_model()

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.fields['username'].label = 'Display Name'
        self.fields['email'].label = 'Email Address'

accounts/views.py
from django.shortcuts import render
from django.core.urlresolvers import reverse_lazy
from django.views.generic import CreateView
from . import forms


from django.dispatch import receiver
from django.db.models.signals import pre_save
from django.contrib.auth.models import User
# Create your views here.

class SignUp(CreateView):
    form_class = forms.UserCreateForm
    success_url = reverse_lazy('login')
    template_name = 'accounts/signup.html'


@receiver(pre_save, sender=User)
def set_new_user_inactive(sender, instance, **kwargs):
    if instance._state.adding is True:
        print("Creating Inactive User")
        instance.is_active = False
    else:
        print("Updating User Record")

attendance/views.py
from django.shortcuts import render
from django.core.urlresolvers import reverse
from . import models
from attendance.models import Session
from django.views.generic import CreateView,ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import views as auth_views
from django.utils import timezone
from django.views.generic import TemplateView


# Create your views here.

class CreateSessionView(LoginRequiredMixin,CreateView):
    fields = ('session',)
    # fields = ('',)
    model = Session
    template_name = "attendance/attendance.html"
    # unique_together = ('session', 'only_date')
    # readonly_fields = ("session",)


    def form_valid(self,form):
        zz = form.save(commit=False)
        zz.user = self.request.user
        # zz.t_date = timezone.localtime()
        return super(CreateSessionView, self).form_valid(form)

    def get_success_url(self):
        return reverse('attendance:list')

class DetailSessionView(LoginRequiredMixin,ListView):

    model = Session
    template_name = 'attendance/view_attendance.html'

    def get_queryset(self):
        return Session.objects.filter(user_id=self.request.user).order_by('-t_date')
#
# class IndexPageView(TemplateView):
#     template_name = 'index.html'

simplesocial/views.py
from django.views.generic import TemplateView

class HomePage(TemplateView):
    template_name = 'index.html'
class TestPage(TemplateView):
    template_name = 'test.html'
class ThanksPage(TemplateView):
    template_name = 'thanks.html'

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content%}
  <div class="container">
    <h1>Log In</h1>
    <form method="POST">
      {% csrf_token %}
      {% bootstrap_form form %}
      <input type="submit" class='btn btn-default' value="Login">
    </form>
  </div>
{% endblock%}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content%}
  <div class="container">
    <h1>Sign Up!</h1>
    <form method="POST">
      {% csrf_token %}
      {% bootstrap_form form %}
      <input type="submit" class='btn btn-default' value="Sign Up">
    </form>
  </div>
{% endblock%}

attendance/templates/attendance/attendance.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% block head %}
  <script>

  function startTime() {
    var today = new Date();
    var h = today.getHours();
    var m = today.getMinutes();
    var s = today.getSeconds();
    m = checkTime(m);
    s = checkTime(s);
    document.getElementById('txt').innerHTML =
    h + ":" + m + ":" + s;
    var t = setTimeout(startTime, 500);
  }
  function checkTime(i) {
    if (i < 10) {i = "0" + i};  // add zero in front of numbers < 10
    return i;
  }
  </script>
{% endblock %}
{% block content %}
  <div class="container">
    <div class="jumbotron">
      <center>
      {# Time #}
      <div class="time">
          <h1><body onload="startTime()"><div id="txt"></div></h1>
      </div>
      <center>
      <h2>Hello {{ request.user.username }}, please select your Session:</h2>
      <br>
      <form method="POST" action="{% url 'attendance:create' %}">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="Mark Attendence" class='btn btn-primary btn-large'>
      </form>
    </div>
  </center>
  </div>
{% endblock %}

attendance/templates/attendance/view_attendance.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% block head %}
  <style media="screen">
    table {
        color: #333;
        font-family: Helvetica, Arial, sans-serif;
        width: 1200px;
        height: 100px;
        border-collapse: collapse;
        border-spacing: 0;
    }
  </style>
{% endblock %}
{% block content %}
<div class="container">
  <div class="jumbotron">
    <center>
      <h2>Hello {{ request.user.username }}, Your Attendance is Listed here:</h2>
    </center>
  </div>
  <center>
  <div class="container">
    {% if session_list %}
      <table class='table-bordered' cellpadding="4" border="">
        <thead>
          <th><center>Session</center></th>
          <th><center>Date & Time</center></th>
        </thead>
      {% for session in session_list %}
      <tr>
        <td><center>{{ session.session }}</center></td>
        <td><center>{{ session.t_date }}</center></td>
      </tr>
      {% endfor %}
      </table>
    {% else %}
      <p>No Session Records Found!!</p>
    {% endif %}
  </center>
  </div>
  </div>
  <br><br>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Onio Seller Services Pvt Ltd</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    {# Google Font: Montserrat#}
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    {# linking master.css #}
    <link rel="stylesheet" href="{% static 'simplesocial/css/master.css' %}">

    {% block head %}{% endblock %}

  </head>
  <body>
    <nav class='navbar mynav' role='navigation' id='navbar'>
      <div class="container">
        <a class='navbar-brand mynav' href="{% url 'home' %}">ONIO</a>
        <ul class='nav navbar-nav navbar-right'>
          <li><a href="http://onioindia.com/">OnioIndia</a></li>
          {% if user.is_authenticated %}
            <li><a href="{% url 'attendance:create' %}">Mark Attendence</a></li>
            <li><a href="{% url 'attendance:list' %}">View Attendence</a></li>
            <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
          {% else %}
            <li><a href="{% url 'accounts:login' %}">Log In</a></li>
            <li><a href="{% url 'accounts:signup' %}">Sign Up</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>
    <div class="container mycontent">
      {% block content %}

      {% endblock %}
    </div>


  </body>
</html>

templates/index.html
{% extends 'base.html' %}
{% block content %}
  <h1>Welcome to <strong>Onio Attendence Portal!</strong></h1>
  <h3>Quickly Mark your Attendence by going on the "<strong>Mark Attendence</strong>" link above  ^</h3>
  <br><br>
  <p>Please Note: <br> Your Attendence will be marked in two Sessions, i.e.,
    <ol>
      <li><strong>Morning</strong></li>
      <li><strong>Evening</strong></li>
    </ol>
    <br>Also, You can ONLY Mark your Attendence in the respective Timings(IST):
    <br><br>
    <ol>
      <li><strong>Morning:</strong> 9:00AM to 9:30AM</li>
      <li><strong>Evening:</strong> 6:30PM to 9:00PM</li>
    </ol>
  </p>
{% endblock %}

templates/test.html
{% extends 'base.html' %}
{% block content %}
  <h1>You Are Now LOGGED IN!</h1>
  <h1>Go to this page http://127.0.0.1:8000/attendance/hi/</h1>
{% endblock %}

templates/thanks.html
{% extends 'base.html' %}
{% block content %}
  <h1>Thanks for Visiting, Back To Work!</h1>
{% endblock %}